title: Devi Parikh
email: deviparikh@gmail.com
description: Confluence | Generative Art
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.cc.gatech.edu/~parikh/confluence/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
include: ['_pages']
ga_id: UA-119138789-1